name = "FerriteVis"
uuid = "59d0093e-b1f1-4fb7-ac85-ab57e45f39d9"
authors = ["Maximilian Köhler <maximilian.koehler@ruhr-uni-bochum.de> and contributors"]
version = "0.1.0"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[compat]
Ferrite = "0.3"
Makie = "0.15, 0.16"
julia = "1"
Tensors = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
